api:
  ip: 0.0.0.0
  port: 8100

dsn: postgresql://cryptotrader:test@db/cryptotrader
redis_dsn: redis://redis:6379/0

app:
  # interval between app iteration steps
  interval: 10

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default-formatter:
      format: '%(asctime)s %(levelname)-7s [%(name)-44s] %(message)s'
  handlers:
    default-handler:
      class: logging.StreamHandler
      formatter: default-formatter
      level: DEBUG
  loggers:
      cryptotrader:
        level: DEBUG
        handlers:
          - default-handler

strategies:
  test:
    type: arbitrage
    # max_spend_part = 0.99 - 99% of funds will be used for arbitrage window processing.
    max_spend_part: 1.0
    # width = 1.2 - arbitrage works with profit from 20%
    # width = 0.8 - arbitrage works with profit from -20%
    window_direct_width: 1.03
    # reversed_width should be
    # less or equal window_direct_width!
    window_reversed_width: 1.01
    order_timeout: 30
    fetch_order_interval: 3.0
    order_placement_interval: 5
    autoreverse_order_delta: 172800
    order_type: limit  # or "market"
    exchanges:
      - bitfinex
      - bittrex
    pairs:
      - LTCUSD
      - BTCUSD
      - ETHUSD
      - XMRUSD
      - ZECUSD
      - ETCUSD
      - ETHBTC
      - LTCBTC

# every exchange from `exchanges` section
# will inherit this values by default.
default_exchange:
  fee: 0.01
  limit: 0
  fetch_balances_interval: 1.0
  update_tickers_interval: 10.0
  update_tickers_timeout: 8.0
  pair_name_template: '{quote}{base}'
  pairs:
    - LTCUSD
    - BTCUSD
    - ETHUSD
    - XMRUSD
    - ZECUSD
    - ETCUSD
    - ETHBTC
    - LTCBTC
  # list of pair quote min amounts
  pair_limits:
    DEFAULT: 1.0
    LTCUSD: 0.1
    BTCUSD: 0.02
    ETHUSD: 0.8
    ETCUSD: 0.8

exchanges:
  bitfinex:
    transport:
      websocket_base_url: wss://api.bitfinex.com/ws/2
      http_base_url: https://api.bitfinex.com/v1
      key: ''
      secret: ''
  bittrex:
    pair_name_template: '{base}-{quote}'
    currencies_map:
      USD: USDT
    transport:
      rate_limit:
        limit: 60
        period: 60.0
      http_base_url: https://bittrex.com/api/v1.1
      key: ''
      secret: ''
  hitbtc:
    fetch_balances_interval: 3.0
    transport:
      rate_limit:
        limit: 60
        period: 60.0
      http_base_url: https://api.hitbtc.com/api/2
      key: ''
      secret: ''
